### ISSUE TITLE
up and down both iterate forward

### ISSUE THREAD

**Issue by dubiousdavid** [joshuafcole/claire#10] opened 2014-04-18 16:50 UTC
I’m using Claire 0.1.7 on OS X Mavericks.  The up and down arrows both iterate forward.  According to the keymap, up is suppose to to move in the reverse direction.

**Comment by joshuafcole** [comment] 2014-04-18 18:42
I can confirm this, I'll get it fixed tonight. Sorry for the trouble!

**Comment by dubiousdavid** [comment] 2014-04-18 18:43
Thanks Josh, and thanks for the plugin.

**Comment by joshuafcole** [comment] 2014-04-20 04:41
I've fixed this locally. It was caused by my switch from registering claire commands as CM actions (as it was before the plugin API was released) to registering proper commands. I'll push the fix tonight along with some other miscellaneous fixes and improvements.

Cheers!

**Comment by joshuafcole** [comment] 2014-04-20 05:13
Fixed in 0.1.8, cheers!

**Closed as completed by joshuafcole** 2014-04-20 05:13 UTC
Labels: bug

**Comment by dubiousdavid** [comment] 2014-04-20 13:43
How do I update a plugin?  Do I have to uninstall it first?

**Comment by dubiousdavid** [comment] 2014-04-20 13:50
Nevermind about updating.  Found refresh plugins command.  Update looks good.  Thanks.
